/**
 * Resolve an ISO 639-1/2/3 language code to its full native + English display name.
 *
 * Uses the browser's built-in Intl.DisplayNames API first (covers 600+ languages),
 * with a hardcoded fallback map for common codes and edge cases.
 */

const fallbackMap: Record<string, string> = {
  aa: 'Afar',
  ab: 'Abkhazian',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'Amharic',
  an: 'Aragonese',
  ar: 'Arabic — العربية',
  as: 'Assamese',
  av: 'Avaric',
  ay: 'Aymara',
  az: 'Azerbaijani',
  ba: 'Bashkir',
  be: 'Belarusian',
  bg: 'Bulgarian — Български',
  bh: 'Bihari',
  bi: 'Bislama',
  bm: 'Bambara',
  bn: 'Bengali — বাংলা',
  bo: 'Tibetan',
  br: 'Breton',
  bs: 'Bosnian',
  ca: 'Catalan',
  ce: 'Chechen',
  ch: 'Chamorro',
  co: 'Corsican',
  cr: 'Cree',
  cs: 'Czech — Čeština',
  cu: 'Church Slavic',
  cv: 'Chuvash',
  cy: 'Welsh — Cymraeg',
  da: 'Danish — Dansk',
  de: 'German — Deutsch',
  dv: 'Divehi',
  dz: 'Dzongkha',
  ee: 'Ewe',
  el: 'Greek — Ελληνικά',
  en: 'English',
  eo: 'Esperanto',
  es: 'Spanish — Español',
  et: 'Estonian — Eesti',
  eu: 'Basque — Euskara',
  fa: 'Persian — فارسی',
  ff: 'Fulah',
  fi: 'Finnish — Suomi',
  fj: 'Fijian',
  fo: 'Faroese',
  fr: 'French — Français',
  fy: 'Western Frisian',
  ga: 'Irish — Gaeilge',
  gd: 'Scottish Gaelic',
  gl: 'Galician',
  gn: 'Guarani',
  gu: 'Gujarati — ગુજરાતી',
  gv: 'Manx',
  ha: 'Hausa',
  he: 'Hebrew — עברית',
  hi: 'Hindi — हिन्दी',
  ho: 'Hiri Motu',
  hr: 'Croatian — Hrvatski',
  ht: 'Haitian Creole',
  hu: 'Hungarian — Magyar',
  hy: 'Armenian — Հայերեն',
  hz: 'Herero',
  ia: 'Interlingua',
  id: 'Indonesian — Bahasa Indonesia',
  ie: 'Interlingue',
  ig: 'Igbo',
  ii: 'Sichuan Yi',
  ik: 'Inupiaq',
  io: 'Ido',
  is: 'Icelandic — Íslenska',
  it: 'Italian — Italiano',
  iu: 'Inuktitut',
  ja: 'Japanese — 日本語',
  jv: 'Javanese',
  ka: 'Georgian — ქართული',
  kg: 'Kongo',
  ki: 'Kikuyu',
  kj: 'Kuanyama',
  kk: 'Kazakh — Қазақ',
  kl: 'Kalaallisut',
  km: 'Khmer — ខ្មែរ',
  kn: 'Kannada — ಕನ್ನಡ',
  ko: 'Korean — 한국어',
  kr: 'Kanuri',
  ks: 'Kashmiri',
  ku: 'Kurdish — Kurdî',
  kv: 'Komi',
  kw: 'Cornish',
  ky: 'Kyrgyz',
  la: 'Latin',
  lb: 'Luxembourgish',
  lg: 'Ganda',
  li: 'Limburgish',
  ln: 'Lingala',
  lo: 'Lao — ລາວ',
  lt: 'Lithuanian — Lietuvių',
  lu: 'Luba-Katanga',
  lv: 'Latvian — Latviešu',
  mg: 'Malagasy',
  mh: 'Marshallese',
  mi: 'Māori',
  mk: 'Macedonian — Македонски',
  ml: 'Malayalam — മലയാളം',
  mn: 'Mongolian — Монгол',
  mr: 'Marathi — मराठी',
  ms: 'Malay — Bahasa Melayu',
  mt: 'Maltese — Malti',
  my: 'Burmese — မြန်မာ',
  na: 'Nauru',
  nb: 'Norwegian Bokmål',
  nd: 'North Ndebele',
  ne: 'Nepali — नेपाली',
  ng: 'Ndonga',
  nl: 'Dutch — Nederlands',
  nn: 'Norwegian Nynorsk',
  no: 'Norwegian — Norsk',
  nr: 'South Ndebele',
  nv: 'Navajo',
  ny: 'Chichewa',
  oc: 'Occitan',
  oj: 'Ojibwa',
  om: 'Oromo',
  or: 'Odia — ଓଡ଼ିଆ',
  os: 'Ossetian',
  pa: 'Punjabi — ਪੰਜਾਬੀ',
  pi: 'Pali',
  pl: 'Polish — Polski',
  ps: 'Pashto — پښتو',
  pt: 'Portuguese — Português',
  qu: 'Quechua',
  rm: 'Romansh',
  rn: 'Rundi',
  ro: 'Romanian — Română',
  ru: 'Russian — Русский',
  rw: 'Kinyarwanda',
  sa: 'Sanskrit — संस्कृतम्',
  sc: 'Sardinian',
  sd: 'Sindhi — سنڌي',
  se: 'Northern Sami',
  sg: 'Sango',
  si: 'Sinhala — සිංහල',
  sk: 'Slovak — Slovenčina',
  sl: 'Slovenian — Slovenščina',
  sm: 'Samoan',
  sn: 'Shona',
  so: 'Somali — Soomaali',
  sq: 'Albanian — Shqip',
  sr: 'Serbian — Српски',
  ss: 'Swati',
  st: 'Southern Sotho',
  su: 'Sundanese',
  sv: 'Swedish — Svenska',
  sw: 'Swahili — Kiswahili',
  ta: 'Tamil — தமிழ்',
  te: 'Telugu — తెలుగు',
  tg: 'Tajik — Тоҷикӣ',
  th: 'Thai — ไทย',
  ti: 'Tigrinya',
  tk: 'Turkmen',
  tl: 'Tagalog',
  tn: 'Tswana',
  to: 'Tongan',
  tr: 'Turkish — Türkçe',
  ts: 'Tsonga',
  tt: 'Tatar',
  tw: 'Twi',
  ty: 'Tahitian',
  ug: 'Uyghur — ئۇيغۇرچە',
  uk: 'Ukrainian — Українська',
  ur: 'Urdu — اردو',
  uz: 'Uzbek — Oʻzbek',
  ve: 'Venda',
  vi: 'Vietnamese — Tiếng Việt',
  vo: 'Volapük',
  wa: 'Walloon',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Yiddish — ייִדיש',
  yo: 'Yoruba — Yorùbá',
  za: 'Zhuang',
  zh: 'Chinese — 中文',
  zu: 'Zulu — isiZulu',

  // Common 3-letter codes / variants
  und: 'Unknown',
  mul: 'Multiple Languages',
  zxx: 'No Linguistic Content',
  mis: 'Uncoded Language',
  qaa: 'Reserved',
  cmn: 'Mandarin Chinese — 普通话',
  yue: 'Cantonese — 粵語',
  fil: 'Filipino',
  hbs: 'Serbo-Croatian',
  nob: 'Norwegian Bokmål',
  nno: 'Norwegian Nynorsk',
  por: 'Portuguese — Português',
  spa: 'Spanish — Español',
  fra: 'French — Français',
  deu: 'German — Deutsch',
  zho: 'Chinese — 中文',
  jpn: 'Japanese — 日本語',
  kor: 'Korean — 한국어',
  hin: 'Hindi — हिन्दी',
  ara: 'Arabic — العربية',
  rus: 'Russian — Русский',
  ita: 'Italian — Italiano',
  tur: 'Turkish — Türkçe',
  pol: 'Polish — Polski',
  nld: 'Dutch — Nederlands',
  tha: 'Thai — ไทย',
  vie: 'Vietnamese — Tiếng Việt',
  ind: 'Indonesian — Bahasa Indonesia',
  msa: 'Malay — Bahasa Melayu',
  ben: 'Bengali — বাংলা',
  tam: 'Tamil — தமிழ்',
  tel: 'Telugu — తెలుగు',
  mar: 'Marathi — मराठी',
  urd: 'Urdu — اردو',
  guj: 'Gujarati — ગુજરાતી',
  kan: 'Kannada — ಕನ್ನಡ',
  mal: 'Malayalam — മലയാളം',
  pan: 'Punjabi — ਪੰਜਾਬੀ',
  ori: 'Odia — ଓଡ଼ିଆ',
  sin: 'Sinhala — සිංහල',
  nep: 'Nepali — नेपाली',
  eng: 'English',
  ron: 'Romanian — Română',
  ces: 'Czech — Čeština',
  ell: 'Greek — Ελληνικά',
  heb: 'Hebrew — עברית',
  fas: 'Persian — فارسی',
  ukr: 'Ukrainian — Українська',
  cat: 'Catalan',
  hrv: 'Croatian — Hrvatski',
  slk: 'Slovak — Slovenčina',
  slv: 'Slovenian — Slovenščina',
  bul: 'Bulgarian — Български',
  dan: 'Danish — Dansk',
  fin: 'Finnish — Suomi',
  hun: 'Hungarian — Magyar',
  lit: 'Lithuanian — Lietuvių',
  lav: 'Latvian — Latviešu',
  est: 'Estonian — Eesti',
  swe: 'Swedish — Svenska',
  nor: 'Norwegian — Norsk',
  mkd: 'Macedonian — Македонски',
  sqi: 'Albanian — Shqip',
  srp: 'Serbian — Српски',
  bos: 'Bosnian',
  hye: 'Armenian — Հայերեն',
  kat: 'Georgian — ქართული',
  kaz: 'Kazakh — Қазақ',
  mon: 'Mongolian — Монгол',
  mya: 'Burmese — မြန်မာ',
  khm: 'Khmer — ខ្មែរ',
  lao: 'Lao — ລາວ',
  amh: 'Amharic',
  som: 'Somali — Soomaali',
  swa: 'Swahili — Kiswahili',
  hau: 'Hausa',
  yor: 'Yoruba — Yorùbá',
  ibo: 'Igbo',
  zul: 'Zulu — isiZulu',
};

// Try Intl.DisplayNames first (modern browsers), fallback to our map
let _displayNames: Intl.DisplayNames | null = null;
try {
  _displayNames = new Intl.DisplayNames(['en'], { type: 'language', languageDisplay: 'standard' });
} catch {
  // Not supported
}

/**
 * Get a full human-readable language name for a language code.
 * e.g. "en" → "English", "ja" → "Japanese — 日本語", "und" → "Unknown"
 */
export function getLanguageName(code: string): string {
  if (!code) return 'Unknown';

  const normalized = code.trim().toLowerCase().split('-')[0]; // "en-US" → "en"

  // 1. Check our rich fallback map first (has native script names)
  if (fallbackMap[normalized]) {
    return fallbackMap[normalized];
  }

  // 2. Try Intl.DisplayNames for codes not in our map
  if (_displayNames) {
    try {
      const name = _displayNames.of(code);
      if (name && name !== code) {
        // Capitalize first letter
        return name.charAt(0).toUpperCase() + name.slice(1);
      }
    } catch {
      // Invalid code
    }
  }

  // 3. Last resort: return the code itself, capitalized
  return code.toUpperCase();
}
